### ISSUE TITLE
Субтитры с сайта Notabenoid

### ISSUE THREAD

**Issue by VldGrdv** [whatifrussian/notabenoid_markdown#1]
Имеется ли у Вас программа (скрипт) для выкачивания готовых субтитров с обновленной версии сайта Notabenoid?

Пример ссылок на открытые субтитры:

http://nb.romakhin.ru/book/55288
http://notabenoid.org/book/55288

Пример ссылок на закрытые субтитры:

http://nb.romakhin.ru/book/57791
http://notabenoid.org/book/57791

**Comment by Totktonada** [comment]
Вообще, нет.

Но нашелся на диске костыль в духе «писал пять минут», написаный для одной специфической задачи. Если прикрутить requests и выкинуть специфичное, то может Вам подойти. Сам скрипт: https://gist.github.com/Totktonada/c1b3b097451b76d2200d . Берет из файла html страницы перевода с Notabenoid’а, вытаскивает оригиналы и переводы, немного их парсит и выводит в определенном формате.

**Comment by VldGrdv** [comment]
попытаюсь прикрутить, может что путное выйдет.
